"""add parent_id and chunk_type

Revision ID: c9bd121b6642
Revises: a2098fc2d8d3
Create Date: 2026-06-02 18:59:13.501255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9bd121b6642'
down_revision: Union[str, Sequence[str], None] = 'a2098fc2d8d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('parent_id', sa.String(), nullable=True))
    op.add_column('chunks', sa.Column('chunk_type', sa.String(), nullable=False))
    op.create_index(op.f('ix_chunks_parent_id'), 'chunks', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_parent_id'), table_name='chunks')
    op.drop_column('chunks', 'chunk_type')
    op.drop_column('chunks', 'parent_id')
    # ### end Alembic commands ###
